2024-02-04 17:39:39 ERROR Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 116, in _service_connect
    svc_iface._svc_connect(port=port)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 30, in _svc_connect
    self._sock_client.connect(port=port)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/cli/cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/cli/cli.py", line 244, in login
    wandb.setup(settings=login_settings)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 153, in __init__
    wandb._sentry.reraise(e)
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 151, in __init__
    self._service_connect()
  File "/Users/lihongxuan/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 125, in _service_connect
    raise ManagerConnectionRefusedError(message)
wandb.sdk.wandb_manager.ManagerConnectionRefusedError: Connection to wandb service failed: [Errno 61] Connection refused. 

2024-02-05 00:10:22 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:10:39 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:10:40 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:10:41 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:10:42 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:10:47 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:29 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:30 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:38 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:41 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:48 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:55 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:57 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:11:58 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:01 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:14 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:20 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:27 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:38 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:44 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:12:54 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:02 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:13 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:27 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:28 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:32 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:32 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:34 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:37 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:43 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:46 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:46 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:50 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:13:57 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:14:00 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2024-02-05 00:14:00 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
