2024-02-10 11:02:56,350 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-10 11:02:56,351 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Configure stats pid to 59462
2024-02-10 11:02:56,351 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-10 11:02:56,351 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/settings
2024-02-10 11:02:56,351 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-10 11:02:56,351 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-10 11:02:56,351 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-10 11:02:56,352 INFO    MainThread:59462 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_110256-4dai7ckm/logs/debug.log
2024-02-10 11:02:56,352 INFO    MainThread:59462 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_110256-4dai7ckm/logs/debug-internal.log
2024-02-10 11:02:56,352 INFO    MainThread:59462 [wandb_init.py:init():566] calling init triggers
2024-02-10 11:02:56,353 INFO    MainThread:59462 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-10 11:02:56,354 INFO    MainThread:59462 [wandb_init.py:init():591] re-initializing run, found existing run on stack: jqx01fzn
2024-02-10 11:02:56,359 INFO    MainThread:59462 [wandb_run.py:_finish():1962] finishing run aipi549/aipi540/jqx01fzn
2024-02-10 11:02:56,360 INFO    MainThread:59462 [jupyter.py:save_history():445] not saving jupyter history
2024-02-10 11:02:56,360 INFO    MainThread:59462 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-10 11:02:56,360 INFO    MainThread:59462 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-10 11:02:56,360 INFO    MainThread:59462 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-10 11:02:56,361 INFO    MainThread:59462 [wandb_run.py:_restore():2185] restore
2024-02-10 11:02:56,361 INFO    MainThread:59462 [wandb_run.py:_restore():2191] restore done
2024-02-10 11:02:59,077 INFO    MainThread:59462 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-10 11:02:59,078 INFO    MainThread:59462 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-10 11:02:59,397 INFO    MainThread:59462 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-02-10 11:02:59,691 INFO    MainThread:59462 [wandb_init.py:init():616] starting backend
2024-02-10 11:02:59,691 INFO    MainThread:59462 [wandb_init.py:init():620] setting up manager
2024-02-10 11:02:59,694 INFO    MainThread:59462 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-02-10 11:02:59,694 INFO    MainThread:59462 [wandb_init.py:init():628] backend started and connected
2024-02-10 11:02:59,714 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-10 11:02:59,714 INFO    MainThread:59462 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-10 11:02:59,714 INFO    MainThread:59462 [wandb_init.py:init():720] updated telemetry
2024-02-10 11:02:59,767 INFO    MainThread:59462 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-10 11:03:00,587 INFO    MainThread:59462 [wandb_run.py:_on_init():2254] communicating current version
2024-02-10 11:03:00,931 INFO    MainThread:59462 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-10 11:03:00,931 INFO    MainThread:59462 [wandb_init.py:init():804] starting run threads in backend
2024-02-10 11:03:09,029 INFO    MainThread:59462 [wandb_run.py:_console_start():2233] atexit reg
2024-02-10 11:03:09,029 INFO    MainThread:59462 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-02-10 11:03:09,030 INFO    MainThread:59462 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-02-10 11:03:09,030 INFO    MainThread:59462 [wandb_run.py:_redirect():2178] Redirects installed.
2024-02-10 11:03:09,030 INFO    MainThread:59462 [wandb_init.py:init():847] run started, returning control to user process
2024-02-10 11:03:16,895 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-10 11:03:16,895 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Configure stats pid to 59462
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/.config/wandb/settings
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/settings
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_init.py:_log_setup():526] Logging user logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_110316-bl5334oh/logs/debug.log
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/lihongxuan/Desktop/AIPI/Courses/AIPI540/AIPI-540/classifier/wandb/run-20240210_110316-bl5334oh/logs/debug-internal.log
2024-02-10 11:03:16,896 INFO    MainThread:59462 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc9014708b0>
2024-02-10 11:03:16,897 INFO    MainThread:59462 [wandb_init.py:init():566] calling init triggers
2024-02-10 11:03:16,897 INFO    MainThread:59462 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-10 11:03:16,897 INFO    MainThread:59462 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 4dai7ckm
2024-02-10 11:03:16,901 INFO    MainThread:59462 [wandb_run.py:_finish():1962] finishing run aipi549/aipi540/4dai7ckm
2024-02-10 11:03:16,901 INFO    MainThread:59462 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-10 11:03:16,901 INFO    MainThread:59462 [wandb_run.py:_restore():2185] restore
2024-02-10 11:03:16,901 INFO    MainThread:59462 [wandb_run.py:_restore():2191] restore done
2024-02-10 11:03:20,047 INFO    MainThread:59462 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-10 11:03:20,047 INFO    MainThread:59462 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-10 11:03:20,050 INFO    MainThread:59462 [wandb_run.py:_footer_sync_info():3816] logging synced files
